### ISSUE TITLE
Error while running scripts

### ISSUE THREAD

**Issue by pritomrajkhowa** [imatge-upc/VNeAT#5]
c:\VNeAT\VNeAT>python vneat-show_visualizer.py --help
Traceback (most recent call last):
  File "vneat-show_visualizer.py", line 11, in <module>
    from vneat import helper_functions
  File "c:\VNeAT\VNeAT\vneat\helper_functions.py", line 8, in <module>
    from vneat.Processors.MixedProcessor import MixedProcessor
  File "c:\VNeAT\VNeAT\vneat\Processors\MixedProcessor.py", line 6, in <module>
    from vneat.Fitters.CurveFitting import CombinedFitter, CurveFitter
  File "c:\VNeAT\VNeAT\vneat\Fitters\CurveFitting.py", line 6, in <module>
    from vneat.FitScores.FitEvaluation import evaluation_function as eval_func
  File "c:\VNeAT\VNeAT\vneat\FitScores\FitEvaluation.py", line 90
    class evaluation_function(object, metaclass = dictlike):
                                                ^
SyntaxError: invalid syntax

**Comment by ecalabr** [comment]
In case someone else gets stuck here...

First, this package works in python 3.x and was apparently updated to run on 3.x at some point despite what the installation instructions say. 

If you want to make it work in 2.7, then you need to remove ```metaclass = dictlike``` from line 90 of FitEvaluation.py and un-comment line 91: ```__metaclass__ = dictlike```. (see [this explaination](https://portingguide.readthedocs.io/en/latest/classes.html#metaclasses)). There may be additional changes necessary... I ended up just running this in python 3.7 without making this edit.

Also, you need to make sure you have an environment variable named DEBUG. For example: 
```export DEBUG=False``` in your shell before running the scripts.

Hope this helps.
